### ISSUE TITLE
will release the training and testing code?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [GuoleiSun/Indiscernible-Object-Counting#1]

**Comment by ZhaochongAn** [comment]
Hi, thank you for the interests in our work. Yes, we will release the code. Stay tuned for the update!

**Comment by wenyifromsichuan** [comment]
Hello ZhaochongAn, I hope you're doing well. I wanted to kindly inquire if there are any plans to make the Annotation tools available on GitHub? Thank you for your time.

**Comment by GuoleiSun** [comment]
Hi, we do not plan to share the annotation tools. If you need code, please let us know.

**Comment by GuoleiSun** [comment]
@wenyifromsichuan, please check your email .

**Comment by zimenglan-sysu-512** [comment]
hi @GuoleiSun 
it seems that there is only one 'readme' file in the 'IOC' directory.

**Comment by GuoleiSun** [comment]
Hi, could you check your email (dongdk.sysu@foxmail.com)?

**Comment by zimenglan-sysu-512** [comment]
oh, i check the email, and get the code. thanks.

**Comment by Honeybadger-LSX** [comment]
Hello GuoleiSun, your process is very excellent, can you share your code? There seems to be a problem with the link to the dataset and it  is unavailable. I am a graduate student. My email is liushuaixin97@gmail.com.

**Comment by GuoleiSun** [comment]
I have updated the link for downloading the dataset. The reason is that my previous subscription of google drive expires. For the code, you could check you email later.

**Comment by Honeybadger-LSX** [comment]
邮件已收到，会尽快回复，祝安！
